name: Feature Request
description: Request a new Feature
title: "[Feature : CATEGORY] "
labels: ["Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature Request!
  - type: textarea
    id: what-missed
    attributes:
      label: What is missing ?
      description: Tell us your ideas
      placeholder: Tell us what you like!
      value: 
    validations:
      required: true
